<?xml version="1.0" encoding="UTF-8"?>

<!-- Author: Ethan Gruber
	Date last modified: March 2026
	Function: This is the first version of the Numishare distribution and metrical analysis interface. The Distribution interface is based on Solr facets. As of March 2019, 
	the metrical analysis interface has been migrated into a new system at visualize/metrical based on APIs that deliver d3.js compliant JSON and CSV downloads,
	with XSLT and Javascript adapted from the Nomisma.org analyses. 
	
	The new distribution interface is available at visualize/distribution, and also derived from local or Nomisma.org SPARQL queries, but the old distribution interface
	based on Solr facet results will remain intact to support visualizing queries directly from the browse interface. The Solr facets were once HTML tables generated by a pipeline
	and embedded in the HTML document for this page and then rendered in the Highcharts library. As of March 2019, the Solr-based distribution results have been migrated to an API for
	JSON results to be displayed in d3.js -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:numishare="https://github.com/ewg118/numishare"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="#all" version="2.0">
	<xsl:include href="../templates.xsl"/>
	<xsl:include href="../functions.xsl"/>
	<xsl:include href="../templates-search.xsl"/>
	<xsl:include href="../vis-solr-templates.xsl"/>

	<xsl:variable name="pipeline">visualize</xsl:variable>
	<xsl:variable name="display_path"/>
	<xsl:variable name="include_path"
		select="
			if (string(//config/theme/themes_url)) then
				concat(//config/theme/themes_url, //config/theme/orbeon_theme)
			else
				concat('http://', doc('input:request')/request/server-name, ':8080/orbeon/themes/', //config/theme/orbeon_theme)"/>

	<!-- request parameters -->
	<xsl:param name="langParam" select="doc('input:request')/request/parameters/parameter[name = 'lang']/value"/>
	<xsl:param name="lang">
		<xsl:choose>
			<xsl:when test="string($langParam)">
				<xsl:value-of select="$langParam"/>
			</xsl:when>
			<xsl:when test="string(doc('input:request')/request//header[name[. = 'accept-language']]/value)">
				<xsl:value-of select="numishare:parseAcceptLanguage(doc('input:request')/request//header[name[. = 'accept-language']]/value)[1]"/>
			</xsl:when>
		</xsl:choose>
	</xsl:param>

	<xsl:param name="q" select="doc('input:request')/request/parameters/parameter[name = 'q']/value"/>
	<xsl:variable name="tokenized_q"/>

	<!-- typological comparison -->
	<xsl:param name="dist" select="doc('input:request')/request/parameters/parameter[name = 'category']/value"/>
	<xsl:param name="compare" select="doc('input:request')/request/parameters/parameter[name = 'compare']/value"/>
	<xsl:param name="numericType" select="doc('input:request')/request/parameters/parameter[name = 'type']/value"/>

	<!-- config variables -->
	<xsl:variable name="url" select="//config/url"/>
	<xsl:variable name="collection_type" select="//config/collection_type"/>
	<!-- load facets into variable -->
	<xsl:variable name="facets" select="//lst[@name = 'facet_fields']" as="node()*"/>


	<xsl:template match="/">
		<html>
			<head>
				<title>
					<xsl:value-of select="//config/title"/>
					<xsl:text>: </xsl:text>
					<xsl:value-of select="numishare:normalizeLabel('header_visualize', $lang)"/>
				</title>
				<link rel="shortcut icon" type="image/x-icon" href="{$include_path}/images/{if (string(//config/favicon)) then //config/favicon else 'favicon.png'}"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"/>

				<xsl:for-each select="//config/includes/include">
					<xsl:choose>
						<xsl:when test="@type = 'css'">
							<link type="text/{@type}" rel="stylesheet" href="{@url}"/>
						</xsl:when>
						<xsl:when test="@type = 'javascript'">
							<script type="text/{@type}" src="{@url}"/>
						</xsl:when>
					</xsl:choose>
				</xsl:for-each>

				<!-- bootstrap -->
				<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
				<script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"/>

				<!-- Add fancyBox -->
				<link rel="stylesheet" href="{$include_path}/css/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen"/>
				<script type="text/javascript" src="{$include_path}/javascript/jquery.fancybox.pack.js?v=2.1.5"/>
				<link type="text/css" href="{$include_path}/css/style.css" rel="stylesheet"/>

				<!-- visualization libraries -->
				<script type="text/javascript" src="{$include_path}/javascript/d3.min.js"/>
				<script type="text/javascript" src="{$include_path}/javascript/d3plus-plot.full.min.js"/>
				<script type="text/javascript" src="{$include_path}/javascript/search_functions.js"/>
				<script type="text/javascript" src="{$include_path}/javascript/visualize_functions.js"/>

				<xsl:call-template name="google_analytics">
					<xsl:with-param name="id" select="//config/google_analytics_tag"/>
				</xsl:call-template>
			</head>
			<body>
				<xsl:call-template name="header"/>
				<xsl:call-template name="body"/>
				<xsl:call-template name="footer"/>
			</body>
		</html>
	</xsl:template>

	<xsl:template name="body">
		<div class="container-fluid">
			<xsl:if test="//config/languages/language[@code = $lang]/@rtl = true()">
				<xsl:attribute name="style">direction: rtl;</xsl:attribute>
			</xsl:if>
			<div class="row">
				<div class="col-md-12">
					<!-- depreciation message -->

					<xsl:if test="$collection_type = 'cointype'">
						<div class="alert alert-box alert-warning">
							<span class="glyphicon glyphicon-info-sign"></span>
							<strong><xsl:value-of select="numishare:regularize_node('note', $lang)"/>:</strong> The distribution analysis interface is
							going to be deprecated in favor of a <a
								href="./visualize/distribution{if (string($langParam)) then concat('?lang=', $langParam) else ''}">new system</a>. The metrical
							analyses have migrated to <a href="./visualize/metrical{if (string($langParam)) then concat('?lang=', $langParam) else ''}"
							>here</a>.</div>
					</xsl:if>


					<h1>
						<xsl:value-of select="numishare:normalizeLabel('header_visualize', $lang)"/>
					</h1>
					<p><xsl:value-of select="numishare:normalizeLabel('visualize_desc', $lang)"/>: <a href="http://wiki.numismatics.org/numishare:visualize"
							target="_blank">http://wiki.numismatics.org/numishare:visualize</a>.</p>

					<!-- March 2019: tabs disabled. Metrical interface linked to new page -->
					<xsl:apply-templates select="/content/response"/>
				</div>
			</div>
		</div>

		<div class="hidden">
			<span id="display_path">
				<xsl:value-of select="$display_path"/>
			</span>
			<span id="path">./</span>
			<div id="searchBox">
				<h3>
					<xsl:value-of select="numishare:normalizeLabel('visualize_add_query', $lang)"/>
				</h3>
				<xsl:call-template name="search_forms"/>
			</div>
			<span id="page">page</span>
		</div>
	</xsl:template>

	<xsl:template match="response">

		<h3>
			<xsl:value-of select="numishare:normalizeLabel('visualize_typological', $lang)"/>
		</h3>

		<div id="distribution">
			<xsl:if test="string($dist) and count($compare) &gt; 0">
				<xsl:call-template name="solr-chart">
					<xsl:with-param name="hidden" select="false()" as="xs:boolean"/>
					<xsl:with-param name="interface">distribution</xsl:with-param>
				</xsl:call-template>
			</xsl:if>

			<xsl:call-template name="solr-distribution-form">
				<xsl:with-param name="page">page</xsl:with-param>
			</xsl:call-template>
		</div>
	</xsl:template>

	
</xsl:stylesheet>
