PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX nm:       <http://nomisma.org/id/>
PREFIX nmo:	<http://nomisma.org/ontology#>
PREFIX dcterms:  <http://purl.org/dc/terms/>
PREFIX skos:	<http://www.w3.org/2004/02/skos/core#>
PREFIX dcmitype:	<http://purl.org/dc/dcmitype/>

ASK {
  BIND (<%URI%> as ?symbol)
  {
    SELECT ?symbol ?side WHERE {
    	{?side nmo:hasControlmark ?symbol}
    	UNION {?children skos:broader+ ?symbol .
              ?side nmo:hasControlmark ?children}
    }
  }
?type nmo:hasObverse|nmo:hasReverse ?side
  { ?object nmo:hasTypeSeriesItem ?type ; 
  	a nmo:NumismaticObject ; 
  	nmo:hasFindspot ?findspot }
  UNION { ?object nmo:hasTypeSeriesItem ?type ; 
  	a nmo:NumismaticObject ; 
  	dcterms:isPartOf ?hoard .
  	?hoard nmo:hasFindspot ?findspot }
  UNION { ?contents a dcmitype:Collection ; 
  	nmo:hasTypeSeriesItem ?type .
  	?object dcterms:tableOfContents ?contents ; 
  	nmo:hasFindspot ?findspot }
}