PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX nm: <http://nomisma.org/id/>
PREFIX nmo: <http://nomisma.org/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?die ?dieLabel ?altDie ?altDieLabel (count(?object) as ?count) ?type ?typeLabel WHERE {
    %STATEMENTS%
} GROUP BY ?die ?dieLabel ?altDie ?altDieLabel ?type ?typeLabel ORDER BY ?dieLabel ?altDieLabel